name: omniscan
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.2
  sqflite: ^2.3.0
  http: ^1.1.2

flutter:
  uses-material-design: true
